python/Python-2.7.13.tar.xz:
  size: 12495628
  object_id: e3371430-eca9-489e-4656-46d4adc55b34
  sha: 18a8f30a0356c751b8d0ea6f76e764cab13ee046
python/pip-9.0.1-py2.py3-none-any.whl:
  size: 1254803
  object_id: f034b9f1-f13c-48f0-682d-02c530d967a0
  sha: c70393185d27ae8b49a117e6dcc18bc5f8f3a1c3
python/setuptools-36.6.0-py2.py3-none-any.whl:
  size: 481102
  object_id: 627fe0fa-3d85-4216-6d9f-cac03d98f184
  sha: ccac2e600ab95de58a08535152ea6f9a73957f17
python/virtualenv-15.1.0-py2.py3-none-any.whl:
  size: 1820727
  object_id: 69c3efc2-60ad-48c5-58d1-2f6fcdcfdc29
  sha: 0def1fa94de51aa56e24eaefe2173df7249e6ded
python/wheel-0.30.0-py2.py3-none-any.whl:
  size: 49751
  object_id: a5e03fc1-b449-41e7-53a5-e7d854035f2f
  sha: 11694b2cfb611fd4accb1135c7d0fef9db4cd926
